# Лінійна алгебра та NumPy

- Вектори та матриці відіграють центральну роль в IDA.
- Матриці - очевидний спосіб зберігання табличних даних.
- Основа лінійної алгебри, яка є мовою всіх алгоритмів аналізу даних (ml, ai тощо).

## Вектори та Матриці

*Вектор* - 1D масив даних 

$\mathbf{v} = \begin{bmatrix} x_1 \\ x_2 \\ ... \\ x_n \end{bmatrix}$

*Матриця* - 2D масив даних

$$
\mathbf{A} = \begin{bmatrix}
x_{11} & x_{12} & ... & x_{1m} \\
x_{21} & x_{22} & ... & x_{2m} \\
... & ... & ... & ... \\
x_{n1} & x_{n2} & ... & x_{nm}
\end{bmatrix}
$$

Існують також узагальнення матриць вищого порядку (так звані *тензори*), які представляють тривимірні або вищі масиви значень. Вони досить широко використовуються в сучасній науці про дані, хоча зазвичай (але, звичайно, не завжди) тензори використовуються лише в значенні «багатовимірного масиву», а не в їхньому справжньому лінійно-алгебраїчному значенні. Тензори як лінійні оператори, що діють, наприклад, на матриці або інші тензори вищого порядку, дещо рідше використовуються в базовій науці про дані.

### Порядок рядків і стовпців

Матриці можуть бути розміщені в пам'яті за рядками або за стовпцями.

$$
\mathbf{A} = \begin{bmatrix}
100 & 80 \\
60 & 80 \\
100 & 100
\end{bmatrix}
$$

За рядками: 100, 80, 60, 80, 100, 100

За стовпцями: 100, 60, 100, 80, 80, 100

По замовчуванню в NumPy порядок за рядками

## Основні операції

**Додавання**: Дві матриці A та B, $[n\times m]$, $A+B=C$ визначається: $C_{ij}=A_{ij}+B_{ij}$

**Транспонування**: Для матриці $A$, $[n\times m]$, транспонована матриця $C=A^{T}$ визначається: $C_{ij}=A_{ji}$

**Множення**: Для матриць $A$ ($[n\times m]$) та $B$ ($[m\times p]$) добуток $C=AB$ ($[n\times p]$) визначається: $C_{ij}=\sum_{k=1}^{m}A_{ik}B_{kj}$

Множення матриць є асоціативним ($(AB)C=A(BC)$), дистрибутивним $A(B+C)=AB+AC$, але не комутативним ($AB\neq BA$).

**Одинична матриця**: Одинична матриця I це квадратна матриця з одиницями на головній діагоналі та нулями в інших позиціях:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & ... & 0 \\
0 & 1 & ... & 0 \\
... & ... & ... & ... \\
0 & 0 & ... & 1
\end{bmatrix}
$$

Для будь-якої матриці $A$: $AI=IA=A$

**Обернена матриця**: Для квадратної матриці $A$, обернена матриця $A^{−1}$ це така матриця, що

$A^{−1}A=AA^{−1}=I$

Не для кожної квадратної матриці існує обернена.

Деякі рівняння: $(AB)^{T}=B^{T}A^{T}$, $(AB)^{-1}=B^{-1}A^{-1}$

Скалярний добуток векторів: $x*y$ = $x^{T}y = \sum_{i=1}^{n}x_{i}y_{i}$;

Норма вектора: $||x||_{2} = \sqrt{\sum_{i=1}^{n}x_{i}^{2}}$


## Масиви Numpy

Створення масиву за допомогою команди `numpy.array` повертає тип `ndarray`. Ви також можете створювати масиви нулів, одиниць або випадкових чисел (у цьому випадку `np.randon.randn` створює матрицю зі стандартними випадковими нормальними елементами, а `np.random.rand` створює рівномірні випадкові елементи).

In [6]:
import numpy as np

b = np.array([-13,9])           
A = np.array([[4,-5], [-2,3]])   
#print(b, "\n")
#print(A, "\n")

#print(np.ones(40), "\n")           # 1D array of ones
#print(np.zeros(4), "\n")          # 1D array of zeros
#print(np.random.rand(40), "\n")         # 1D array of random normal numbers

#print(np.ones((3,4)), "\n")       # 2D array of ones
#print(np.zeros((3,4)), "\n")      # 2D array of zeros
#print(np.random.randn(3,4))       # 2D array of random normal numbers

sigma, mu = 10, 50
print(sigma * np.random.randn(10,10) + mu)  # 2D array of random normal numbers with mean mu and stddev sigma


[[59.84826746 54.6202055  46.60308853 44.97843771 47.75510755 32.92728926
  37.65072464 45.22961969 36.76930603 50.93383565]
 [59.73106134 49.79625816 52.88440576 42.88247714 41.45560219 55.17181386
  50.44299213 60.73521407 50.98441893 63.37158909]
 [46.59995611 55.27716031 36.09245699 69.22993578 43.46543733 48.02862214
  47.00807966 58.06692992 23.66072715 46.26772399]
 [62.2082221  44.43551774 45.26143886 67.22882528 49.62244415 34.90157224
  71.86674352 51.35961906 62.16883849 48.62881638]
 [47.4160745  55.87835297 38.6677695  54.71102112 52.41167056 36.33472234
  66.95975122 72.93134009 58.76958311 48.13077177]
 [46.50954746 48.80100781 36.51883868 43.49420983 47.15142286 25.61087618
  45.55921887 49.75505496 57.83116108 37.16565521]
 [58.10485637 55.05152149 58.81631406 45.11167568 55.8323975  51.51946401
  53.6849051  27.48216758 47.15161746 51.34840152]
 [58.94416448 45.45903083 44.75156541 54.69861056 40.12677761 60.41429235
  71.08986497 47.406803   56.2159903  53.20827585]


Ви також можете створити матрицю ідентичності за допомогою команди `np.eye()`, а діагональну матрицю — за допомогою команди `np.diag()`.

In [7]:
print(np.eye(3),"\n")                     # create array for 3x3 identity matrix
print(np.diag(np.random.randn(3)),"\n")   # create diagonal array

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ 0.50651677  0.          0.        ]
 [ 0.         -0.35063699  0.        ]
 [ 0.          0.         -0.72949183]] 



## Індексація в масивах numpy

In [8]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(A, "\n")
print(A[1,1],"\n")           # select singe entry
print(A[1,:],"\n")           # select entire row
print(A[1:3, :], "\n")       # slice indexing


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

5 

[4 5 6] 

[[4 5 6]
 [7 8 9]] 



In [9]:
print(A[1:2,1:2], "\n")  # Select A[1,1] as a singleton 2D array
print(A[[1,2,3],:], "\n")  # select rows 1, 2, and 3
print(A[[2,1,2],:], "\n")  # select rows 2, 1, and 2 again
print(A[[False, True, False, True],:], "\n")  # Select 1st and 3rd rows

[[5]] 

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[7 8 9]
 [4 5 6]
 [7 8 9]] 

[[ 4  5  6]
 [10 11 12]] 



## Основні операції над масивами

Масиви можна додавати/віднімати, множити/ділити та транспонувати, але ці операції **не є ідентичними** до відповідних операцій у лінійній алгебрі.
Множення та ділення масивів виконуються **поелементно**, вони **не** є множенням матриць або чимось, пов'язаним з оберненням матриць.

In [10]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([[1, 1, 1], [1,2,1], [3, 1, 3], [1, 4, 1]])

print(A+B, "\n") # add A and B elementwise (same as "standard" matrix addition)
print(A-B, "\n") # subtract B from A elementwise (same as "standard" matrix subtraction)
print(A*B, "\n") # elementwise multiplication, _not_ matrix multiplication
print(A/B, "\n") # elementwise division, _not_ matrix inversion

[[ 2  3  4]
 [ 5  7  7]
 [10  9 12]
 [11 15 13]] 

[[ 0  1  2]
 [ 3  3  5]
 [ 4  7  6]
 [ 9  7 11]] 

[[ 1  2  3]
 [ 4 10  6]
 [21  8 27]
 [10 44 12]] 

[[ 1.          2.          3.        ]
 [ 4.          2.5         6.        ]
 [ 2.33333333  8.          3.        ]
 [10.          2.75       12.        ]] 



Ви можете транспонувати масиви, але зверніть увагу, що це має значення тільки для 2D (або вищих) масивів. Транспонування 1D масиву нічого не дає, оскільки Numpy не розрізняє стовпцеві вектори та рядкові вектори для 1D масивів.

In [11]:
print(A, "\n")
print(A.T, "\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] 



## Трансляція Numpy (broadcasting)

Справжня цікавість починається, коли ви додаєте/віднімаєте/множите/ділите масиви різних розмірів. Замість того, щоб видавати помилку, Numpy спробує зрозуміти вашу операцію, використовуючи правила трансляції Numpy. Це складна тема, яка часто бентежить новачків у Numpy, але з невеликою практикою правила стають досить інтуїтивними.

In [13]:
A = np.ones((4,3))          # A is 4x3
x = np.array([[1,2,3]])      # x is 1x3

print(A, '\n')
print(x, '\n')

print(A*x)                          # repeat x along dimension 4 (repeat four times), and multiply A

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1 2 3]] 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## Операції лінійної алгебри

Починаючи з Python 3, між масивами numpy тепер існує оператор множення матриць `@` (раніше для цього доводилося використовувати більш громіздку функцію `np.dot()`).

In [14]:
A = np.random.randn(5,4)
C = np.random.randn(4,3)
x = np.random.randn(4)
y = np.random.randn(5)
z = np.random.randn(4)

print(A @ C, "\n")       # matrix-matrix multiply (returns 2D array)
print(A @ x, "\n")       # matrix-vector multiply (returns 1D array)
print(x @ z)       # inner product (scalar) - be careful about return type, not an ndarray!

[[-0.77983164  0.86915701  0.74016041]
 [ 0.9441811  -1.13337787 -2.45126146]
 [ 1.06065113 -3.17950771 -3.50084458]
 [ 1.26732128 -1.3041138  -2.5499486 ]
 [ 1.60891994 -4.68541868 -4.6433185 ]] 

[ 1.53587182 -2.9122003  -2.53401694 -2.88846645 -3.50775768] 

2.236322572387176


За замовчуванням оператор @ застосовується зліва направо, що може призвести до дуже неефективних порядків множення матриць.

In [ ]:
A = np.random.randn(1000,1000)
B = np.random.randn(1000,2000)
x = np.random.randn(2000)

# B @ x 1000x1

%timeit A @ B @ x
# print(A @ B @ x)

59.1 ms ± 7.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Це виконує матричні добутки $(AB)x$, які спочатку обчислюють неефективне множення матриць. Якщо ми хочемо обчислити добуток у набагато ефективнішому порядку $A(Bx)$, ми використаємо команду

In [16]:
%timeit A @ (B @ x)

2.13 ms ± 226 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**Складність операцій**

Припустимо, що $A$, $B$ [$n\times n$], $x,y$ - вектори [n].

Добуток матриць $AB$: $O(n^{3})$

Добуток матриці та вектора $Ax$: $O(n^{2})$

Внутрішній добуток векторів $x^{T}y$: $O(n)$

Обернена матриця/розв'язання: $A^{-1}$: $O(n^{3})$

Нарешті, Numpy включає процедуру `np.linalg.inv()` для обчислення оберненої матриці $A^{−1}$ та `np.linalg.solve()` для обчислення матричного рівняння $A^{−1}b$.

In [17]:
b = np.array([-13,9])
A = np.array([[4,-5], [-2,3]])

print(np.linalg.inv(A), "\n")   # explicitly form inverse
print(np.linalg.solve(A,b))     # compute solution A^{-1}b

[[1.5 2.5]
 [1.  2. ]] 

[3. 5.]


## Розріджені матриці

Багато матриць є розрідженими (містять переважно нульові елементи, з лише декількома ненульовими 
елементами)

Приклади: матриці, утворені реальними графами, матриці підрахунку слів у документах 
(більше про це пізніше)

Зберігання всіх цих нулів у стандартному форматі матриці може бути великою тратою 
обчислювальних ресурсів і пам'яті

Бібліотеки розріджених матриць надають ефективні засоби для обробки цих розріджених 
матриць, зберігаючи і оперуючи тільки ненульовими елементами

Існує кілька різних способів зберігання розріджених матриць, кожен з яких оптимізований для 
різних операцій

**Формат координат (COO):** зберігання кожного елемента як кортежу
(row_index, col_index, value)

$$
\mathbf{A} = \begin{bmatrix}
0 & 0 & 3 & 0 \\
2 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 \\
4 & 0 & 1 & 0
\end{bmatrix}
$$

Замість:\
$values = [2, 4, 1, 3, 1, 1]$\
$row-indices = [1, 3, 2, 0, 3, 1]$\
$column-indices = [0, 0, 1, 2, 2, 3]$

## Python sparse matrix libraries

https://docs.scipy.org/doc/scipy/reference/sparse.html

In [18]:
import scipy.sparse as sp


values = [2, 4, 1, 3, 1, 1]
row_indices = [1, 3, 2, 0, 3, 1]
column_indices = [0, 0, 1, 2, 2, 3]
A = sp.coo_matrix((values, (row_indices, column_indices)), shape=(4,4))
print(A.todense())

[[0 0 3 0]
 [2 0 0 1]
 [0 1 0 0]
 [4 0 1 0]]
